### ISSUE TITLE
border-radius is not prefixed

### ISSUE THREAD

**Issue by mkantor** [codler/jQuery-Css3-Finalize#12]
The border-radius shorthand property doesn't seem to be getting prefixed correctly.  However, border-top-left-radius, border-top-right-radius, etc work fine.

**Comment by codler** [comment]
What browser are you testing? Most of the browser doesn't need prefixing border-radius anymore. http://caniuse.com/#feat=border-radius

**Comment by mkantor** [comment]
I noticed it in Firefox 3.6, is that browser not supported?

Sorry if this is getting off-topic, but do you have a list of supported/tested browsers?

**Comment by mkantor** [comment]
Also occurs in Safari 4 (as indicated by http://caniuse.com/#feat=border-radius ).

**Comment by codler** [comment]
I usually only test on latest stable version of browsers ( and IE8 ) since they have auto update and will only support those.

Version 1.39 was the last time I tested on FF 3.6 but that version only works up to jQuery 1.5.
Have you an example of how your border-radius shorthand looks like? 
Could it be because of this?
See under `<percentage> values` section https://developer.mozilla.org/en/css/-moz-border-radius#section_8

**Comment by mkantor** [comment]
I'm using `px`.

Here's a test case:
http://jsfiddle.net/afEwj/1/

And here's a screenshot of the test case in both FF 3.6 and Safari 4:
http://i.imgur.com/l17Iy.png

Anyway if these browsers aren't supported that's understandable, but it'd be handy if the README included all version numbers in the list of tested browsers.

**Comment by codler** [comment]
aha, `border-radius: 10px;` have worked before in FF 3.6.

Could you check if this works?
http://jsfiddle.net/afEwj/2/

**Comment by mkantor** [comment]
Success!
http://i.imgur.com/ICJPr.png

**Comment by codler** [comment]
Thanks!
